### ISSUE TITLE
Run SentiCR model

### ISSUE THREAD

**Issue by bcdasilv** [SentimentAnalysisInSE/code_review_analysis#3]
Familiarize yourself with SentiCR by reading the source code (https://github.com/senticr/SentiCR) and skimming through the paper (http://amiangshu.com/papers/senticr-ase.pdf).

Then, run their model in python just to make sure you have your environment ready for our experiments. The dataset we'll use is available in their repo (oracle.xlsx file).

Make sure you understand the following performance metrics: precision, recall, and f-measure.

**Comment by bcdasilv** [comment]
Python modules that I had to install for SentiCR: scikit-learn, nltk, xlrd, and imbalanced-learn. After that I ran into the same error you got. 
<img width="623" alt="Screen Shot 2019-07-02 at 8 07 02 PM" src="https://user-images.githubusercontent.com/6404641/60552578-c068c600-9d05-11e9-8704-095259168d68.png">

**Comment by bcdasilv** [comment]
@steven19992017 if you google the error "TypeError: cannot use a string pattern on a bytes-like object" you're going to find some clue. It seems that the string contents are coming in a format not converted to decoded string. That's why that call is raising a TypeError exception (trying to apply a string operation on a non-string object).

**Comment by steven19992017** [comment]
I solved the format issue using s.decode(). I was able to run the SentiCR mode now. While it runs, outputs the f-measure, accuracy, precision, it gives another error for tokenizing during the preprocessing. Here is the error message:
![image](https://user-images.githubusercontent.com/33203413/62039140-f2a60000-b1ab-11e9-8c6e-368487e890cc.png)
Here is the output that I got after 10 splits:
![image](https://user-images.githubusercontent.com/33203413/62039259-339e1480-b1ac-11e9-994b-67718b2037aa.png)
I am not sure how to solve this. I am not sure if the unprocessed tokens will have any major effect on the output of SentiCR

**Comment by bcdasilv** [comment]
Nice that you were able to solve the previous issue! 

I'm not sure either if that warning represents a major impact. Maybe not because this is the result they reported in the SentiCR paper (see the URL for the paper in the issue description).

This is good you noticed that and let's leave it in standby for now and let's move on to the next tasks.

Please, report how many hours you put in this task.

**Comment by steven19992017** [comment]
Time spent for this task: 6 hours

**Comment by bcdasilv** [comment]
Thanks
