### ISSUE TITLE
Run Pre-built EMTk Model

### ISSUE THREAD

**Issue by bcdasilv** [SentimentAnalysisInSE/code_review_analysis#4]
Familiarize yourself with their documentation: https://github.com/collab-uniba/EMTk
They've provided a version using Docker (prioritize this installation/running mode first). 

You can also skim through their paper if you want: https://arxiv.org/pdf/1903.09525.pdf

Run their pre-built model with the code review dataset from SentiCR repo.
Compare their results (precision, recall, f-measure).

Report the results in our repo wikipage.

**Comment by steven19992017** [comment]
Docker set up on Windows took a long time. The container also took a long time to download since the size of container is around 10GB.
After pulling the container, I am not sure how to run our own data set since the path I tried doesn't work. 
![image](https://user-images.githubusercontent.com/33203413/62585557-31a01980-b86e-11e9-930f-189bf9385c91.png)

**Comment by steven19992017** [comment]
Hours spent so far: 3 hours

**Comment by bcdasilv** [comment]
@steven19992017 , I just ran the docker image and worked well on my computer. The error you got is really something with the way windows deals with path names or the way docker deals with path names on windows.

**Comment by bcdasilv** [comment]
My computer is a Mac (not sure if I mentioned that). 

In addition, they have a toy example there in the image folder as a sample. I tried out the polarity_sample.csv and generated an output.csv and this worked well. So, in your case, it seems to be just a matter of how to pass the path name on a windows host machine.

**Comment by steven19992017** [comment]
I was able to figure out how to bind mount a directory on windows to the linux virtual machine. So I first converted the oracle.xlsx file to oracle.csv format and got rid of the second column. Then I ran the EMTK polarity tool on the new csv file but i ran into a bunch of errors. You mentioned on Slack that you were able to run it by getting rid of the second column. Do you still remember how you did it? 
![image](https://user-images.githubusercontent.com/33203413/63523866-8067d780-c52d-11e9-994d-678aa5b5c952.png)

**Comment by steven19992017** [comment]
Time spent: 4.5 hours

**Comment by bcdasilv** [comment]
That's great you could solve the path issue on windows.

And I didn't run EMTk with the oracle.xls dataset. I only ran with their sample dataset that comes with EMTk image.

Concerning the warning msgs you're getting, first we have to understand what they mean. If they're just warnings and not errors we should not care about, that's fine. Try to google those msgs and and see if you can find more info about those warnings. They're related to the third party lib Stanford NLP. 

Second, take a look at the EMTk issues page on GH. They've reported a bug relate to the "-p" argument. Please, check if you should use the workaround they suggest there, which is always run  with the '-p' but I don't remember if this is for the 'emotion' command only or both (emotion and polarity).

Keep us posted here. Thanks!

**Comment by steven19992017** [comment]
the csv file contents are originally spaced in multiple lines for each cell so running EMTK will result in three times as much results. As seen here:
![image](https://user-images.githubusercontent.com/33203413/63639781-497af880-c6ca-11e9-981e-e46072737b58.png)
So i tried to use python to get rid of all the spaces but ran into bunch of issues like invalid bytes.
Eventually, i was able to get rid of all the new lines in each cell by using an excel function.
So i finally was able to run the EMTK prebulit version on the oracle dataset. Here is the link for the updated oracle.xlsx file. https://drive.google.com/file/d/1pHYSW7MjQI6ZJLFqJOYj3tLQczttDOLK/view?usp=sharing
Comparing the results, it's clear that the prebuilt model doesn't have that much accuracy. I would say probably like 40% correct? So I think we should train our own model

**Comment by steven19992017** [comment]
Hours log: 8 hours

**Comment by steven19992017** [comment]
it seems to me that EMTK only provides option for training our own model for the emotion tool kit. Not the polarity tool kit. I will move onto the next task for now

**Comment by bcdasilv** [comment]
@steven19992017, indeed, based on the readme, it seems that they only support custom models for the emotion module. I hadn't noticed that. To be sure, have you tried the command 'emtk polarity train'? Let's make sure it's really not available besides not being mentioned in the readme.

Supposing it's not available, I still think that it would be important to train a model for code review comments using EMTk. So, in order to do that, let's execute the following strategy. Run the emotions module, by training a new model and then classifying using the 'oracle.xls' dataset. Then, we're going to create a new column on that dataset as a further step. This column will represent whether each row was classified with a 'negative' or 'non-negative' emotion. Please, assume that {joy, love, surprise} are 'non-negative' and {anger, sadness, fear} are 'negative' sentiments. Doing this conversion at the end, we'll make the results comparable.

**Comment by bcdasilv** [comment]
By the way, this task of running our own model I had defined as a separate issue on the board. We should discuss this stuff there. Thanks!

**Comment by bcdasilv** [comment]
@steven19992017 , I forgot to ask you here, how dd you calculate the accuracy of the results for the pre-built EMTk model? You mentioned earlier "I would say probably like 40% correct? ", but how did you come up with that number?

**Comment by bcdasilv** [comment]
[oracle.xlsx](https://github.com/SentimentAnalysisInSE/code_review_analysis/files/3637153/oracle.xlsx)

That's the file with an additional column that represents hits and misses of the classification and on the bottom some accuracy metrics (hits/misses ratio).
